// Code generated by protoc-gen-go. DO NOT EDIT.
// source: filter_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Filter struct {
	MaxPriceUsd          float64  `protobuf:"fixed64,1,opt,name=max_price_usd,json=maxPriceUsd,proto3" json:"max_price_usd,omitempty"`
	MinCpuCores          uint32   `protobuf:"varint,2,opt,name=min_cpu_cores,json=minCpuCores,proto3" json:"min_cpu_cores,omitempty"`
	MinCpuGhz            float64  `protobuf:"fixed64,3,opt,name=min_cpu_ghz,json=minCpuGhz,proto3" json:"min_cpu_ghz,omitempty"`
	MinRam               *Memory  `protobuf:"bytes,4,opt,name=min_ram,json=minRam,proto3" json:"min_ram,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_02dd12c5821a9fa1, []int{0}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetMaxPriceUsd() float64 {
	if m != nil {
		return m.MaxPriceUsd
	}
	return 0
}

func (m *Filter) GetMinCpuCores() uint32 {
	if m != nil {
		return m.MinCpuCores
	}
	return 0
}

func (m *Filter) GetMinCpuGhz() float64 {
	if m != nil {
		return m.MinCpuGhz
	}
	return 0
}

func (m *Filter) GetMinRam() *Memory {
	if m != nil {
		return m.MinRam
	}
	return nil
}

func init() {
	proto.RegisterType((*Filter)(nil), "Filter")
}

func init() {
	proto.RegisterFile("filter_message.proto", fileDescriptor_02dd12c5821a9fa1)
}

var fileDescriptor_02dd12c5821a9fa1 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcb, 0xcc, 0x29,
	0x49, 0x2d, 0x8a, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x97, 0x12, 0xc9, 0x4d, 0xcd, 0xcd, 0x2f, 0xaa, 0x44, 0x15, 0x55, 0x9a, 0xc4, 0xc8, 0xc5, 0xe6,
	0x06, 0x56, 0x2e, 0xa4, 0xc4, 0xc5, 0x9b, 0x9b, 0x58, 0x11, 0x5f, 0x50, 0x94, 0x99, 0x9c, 0x1a,
	0x5f, 0x5a, 0x9c, 0x22, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x18, 0xc4, 0x9d, 0x9b, 0x58, 0x11, 0x00,
	0x12, 0x0b, 0x2d, 0x4e, 0x01, 0xab, 0xc9, 0xcc, 0x8b, 0x4f, 0x2e, 0x28, 0x8d, 0x4f, 0xce, 0x2f,
	0x4a, 0x2d, 0x96, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0d, 0xe2, 0xce, 0xcd, 0xcc, 0x73, 0x2e, 0x28,
	0x75, 0x06, 0x09, 0x09, 0xc9, 0x71, 0x71, 0xc3, 0xd4, 0xa4, 0x67, 0x54, 0x49, 0x30, 0x83, 0x4d,
	0xe1, 0x84, 0xa8, 0x70, 0xcf, 0xa8, 0x12, 0x52, 0xe0, 0x62, 0x07, 0xc9, 0x17, 0x25, 0xe6, 0x4a,
	0xb0, 0x28, 0x30, 0x6a, 0x70, 0x1b, 0xb1, 0xeb, 0xf9, 0x82, 0x9d, 0x16, 0xc4, 0x96, 0x9b, 0x99,
	0x17, 0x94, 0x98, 0xeb, 0xc4, 0x15, 0xc5, 0xa1, 0xa7, 0xa7, 0x5f, 0x90, 0x64, 0x5d, 0x90, 0x94,
	0xc4, 0x06, 0x76, 0xa7, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x94, 0x12, 0x2f, 0xd5, 0x00,
	0x00, 0x00,
}
