// Code generated by protoc-gen-go. DO NOT EDIT.
// source: laptop_message.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Laptop struct {
	Id       string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand    string     `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Name     string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cpu      *CPU       `protobuf:"bytes,4,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Ram      *Memory    `protobuf:"bytes,5,opt,name=ram,proto3" json:"ram,omitempty"`
	Gpus     []*GPU     `protobuf:"bytes,6,rep,name=gpus,proto3" json:"gpus,omitempty"`
	Storages []*Storage `protobuf:"bytes,7,rep,name=storages,proto3" json:"storages,omitempty"`
	Screen   *Screen    `protobuf:"bytes,8,opt,name=screen,proto3" json:"screen,omitempty"`
	Keyboard *Keyboard  `protobuf:"bytes,9,opt,name=keyboard,proto3" json:"keyboard,omitempty"`
	// Types that are valid to be assigned to Weight:
	//	*Laptop_WeightKg
	//	*Laptop_WeightLb
	Weight               isLaptop_Weight `protobuf_oneof:"weight"`
	PriceUsd             float64         `protobuf:"fixed64,12,opt,name=price_usd,json=priceUsd,proto3" json:"price_usd,omitempty"`
	ReleaseYear          uint32          `protobuf:"varint,13,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Laptop) Reset()         { *m = Laptop{} }
func (m *Laptop) String() string { return proto.CompactTextString(m) }
func (*Laptop) ProtoMessage()    {}
func (*Laptop) Descriptor() ([]byte, []int) {
	return fileDescriptor_07a3824d46f4b731, []int{0}
}

func (m *Laptop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Laptop.Unmarshal(m, b)
}
func (m *Laptop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Laptop.Marshal(b, m, deterministic)
}
func (m *Laptop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Laptop.Merge(m, src)
}
func (m *Laptop) XXX_Size() int {
	return xxx_messageInfo_Laptop.Size(m)
}
func (m *Laptop) XXX_DiscardUnknown() {
	xxx_messageInfo_Laptop.DiscardUnknown(m)
}

var xxx_messageInfo_Laptop proto.InternalMessageInfo

func (m *Laptop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Laptop) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Laptop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Laptop) GetCpu() *CPU {
	if m != nil {
		return m.Cpu
	}
	return nil
}

func (m *Laptop) GetRam() *Memory {
	if m != nil {
		return m.Ram
	}
	return nil
}

func (m *Laptop) GetGpus() []*GPU {
	if m != nil {
		return m.Gpus
	}
	return nil
}

func (m *Laptop) GetStorages() []*Storage {
	if m != nil {
		return m.Storages
	}
	return nil
}

func (m *Laptop) GetScreen() *Screen {
	if m != nil {
		return m.Screen
	}
	return nil
}

func (m *Laptop) GetKeyboard() *Keyboard {
	if m != nil {
		return m.Keyboard
	}
	return nil
}

type isLaptop_Weight interface {
	isLaptop_Weight()
}

type Laptop_WeightKg struct {
	WeightKg float64 `protobuf:"fixed64,10,opt,name=weight_kg,json=weightKg,proto3,oneof"`
}

type Laptop_WeightLb struct {
	WeightLb float64 `protobuf:"fixed64,11,opt,name=weight_lb,json=weightLb,proto3,oneof"`
}

func (*Laptop_WeightKg) isLaptop_Weight() {}

func (*Laptop_WeightLb) isLaptop_Weight() {}

func (m *Laptop) GetWeight() isLaptop_Weight {
	if m != nil {
		return m.Weight
	}
	return nil
}

func (m *Laptop) GetWeightKg() float64 {
	if x, ok := m.GetWeight().(*Laptop_WeightKg); ok {
		return x.WeightKg
	}
	return 0
}

func (m *Laptop) GetWeightLb() float64 {
	if x, ok := m.GetWeight().(*Laptop_WeightLb); ok {
		return x.WeightLb
	}
	return 0
}

func (m *Laptop) GetPriceUsd() float64 {
	if m != nil {
		return m.PriceUsd
	}
	return 0
}

func (m *Laptop) GetReleaseYear() uint32 {
	if m != nil {
		return m.ReleaseYear
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Laptop) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Laptop_WeightKg)(nil),
		(*Laptop_WeightLb)(nil),
	}
}

func init() {
	proto.RegisterType((*Laptop)(nil), "Laptop")
}

func init() {
	proto.RegisterFile("laptop_message.proto", fileDescriptor_07a3824d46f4b731)
}

var fileDescriptor_07a3824d46f4b731 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0xd1, 0x41, 0x6b, 0xa3, 0x40,
	0x14, 0x07, 0xf0, 0x35, 0x1a, 0x33, 0xbe, 0x24, 0x7b, 0x18, 0xb2, 0xd9, 0xd9, 0x5d, 0x96, 0x75,
	0x4b, 0x0b, 0x9e, 0x2c, 0xb4, 0xc7, 0xde, 0xd2, 0x43, 0x0b, 0x49, 0x21, 0x4c, 0xc8, 0xa1, 0xbd,
	0xc8, 0xa8, 0x0f, 0x2b, 0x89, 0x99, 0x61, 0xc6, 0x50, 0xf2, 0x01, 0xfa, 0xbd, 0x4b, 0x46, 0x1b,
	0x1a, 0x6f, 0xbe, 0xdf, 0xff, 0xf9, 0xf0, 0x8f, 0x30, 0xd9, 0x0a, 0x55, 0x4b, 0x95, 0x54, 0x68,
	0x8c, 0x28, 0x30, 0x56, 0x5a, 0xd6, 0xf2, 0xf7, 0x4f, 0xa5, 0x65, 0x86, 0xc6, 0x48, 0xdd, 0x09,
	0x26, 0x15, 0x56, 0x52, 0x1f, 0x3a, 0xfa, 0xc3, 0xd4, 0x52, 0x8b, 0x02, 0xbb, 0xcb, 0x26, 0xd3,
	0x88, 0xbb, 0x8e, 0x4e, 0x37, 0x78, 0x48, 0xa5, 0xd0, 0xf9, 0xb9, 0x5f, 0xbc, 0xbb, 0xe0, 0x2f,
	0xec, 0xc7, 0xd0, 0xef, 0xd0, 0x2b, 0x73, 0xe6, 0x84, 0x4e, 0x14, 0xf0, 0x5e, 0x99, 0xd3, 0x09,
	0xf4, 0x53, 0x2d, 0x76, 0x39, 0xeb, 0x59, 0x6a, 0x06, 0x4a, 0xc1, 0xdb, 0x89, 0x0a, 0x99, 0x6b,
	0xd1, 0x3e, 0xd3, 0x29, 0xb8, 0x99, 0xda, 0x33, 0x2f, 0x74, 0xa2, 0xe1, 0x8d, 0x17, 0xdf, 0x2f,
	0xd7, 0xfc, 0x08, 0xf4, 0x17, 0xb8, 0x5a, 0x54, 0xac, 0x6f, 0x7d, 0x10, 0x3f, 0xd9, 0x16, 0xfc,
	0x68, 0x94, 0x81, 0x57, 0xa8, 0xbd, 0x61, 0x7e, 0xe8, 0xda, 0x77, 0x1e, 0x96, 0x6b, 0x6e, 0x85,
	0x5e, 0x02, 0x69, 0x8b, 0x19, 0x36, 0xb0, 0x29, 0x89, 0x57, 0x0d, 0xf0, 0x53, 0x42, 0xff, 0x81,
	0xdf, 0xf4, 0x64, 0xa4, 0xbd, 0xbe, 0xb2, 0x23, 0x6f, 0x99, 0x5e, 0x01, 0xf9, 0xac, 0xcc, 0x02,
	0xbb, 0x12, 0xc4, 0xf3, 0x16, 0xf8, 0x29, 0xa2, 0x7f, 0x21, 0x78, 0xc3, 0xb2, 0x78, 0xad, 0x93,
	0x4d, 0xc1, 0x20, 0x74, 0x22, 0xe7, 0xf1, 0x1b, 0x27, 0x0d, 0xcd, 0x8b, 0x2f, 0xf1, 0x36, 0x65,
	0xc3, 0xf3, 0x78, 0x91, 0xd2, 0x3f, 0x10, 0x28, 0x5d, 0x66, 0x98, 0xec, 0x4d, 0xce, 0x46, 0xc7,
	0x98, 0x13, 0x0b, 0x6b, 0x93, 0xd3, 0xff, 0x30, 0xd2, 0xb8, 0x45, 0x61, 0x30, 0x39, 0xa0, 0xd0,
	0x6c, 0x1c, 0x3a, 0xd1, 0x98, 0x0f, 0x5b, 0x7b, 0x46, 0xa1, 0x67, 0x04, 0xfc, 0xe6, 0xd6, 0x0c,
	0x5e, 0x48, 0x1c, 0x5f, 0xab, 0xf4, 0x4e, 0xa5, 0xa9, 0x6f, 0x7f, 0xcd, 0xed, 0x47, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x21, 0x07, 0xec, 0xa6, 0x26, 0x02, 0x00, 0x00,
}
